# Generated by Django 6.0.3 on 2026-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userCarbonTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('electricity_usage', models.FloatField(default=0.0)),
                ('transport_km', models.FloatField(default=0.0)),
                ('carbon_result', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
