# Generated by Django 6.0.3 on 2026-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercarbontracker',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل تتبع الكربون', 'verbose_name_plural': 'سجلات تتبع الكربون'},
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='age',
            field=models.PositiveIntegerField(verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='carbon_result',
            field=models.FloatField(blank=True, null=True, verbose_name='نتيجة الكربون'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='city',
            field=models.CharField(max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='electricity_usage',
            field=models.FloatField(default=0.0, help_text='الاستهلاك بالكيلوواط ساعة (kWh)'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='transport_km',
            field=models.FloatField(default=0.0, help_text='المسافة المقطوعة بالكيلومتر'),
        ),
    ]
