# Generated by Django 6.0.3 on 2026-05-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_usercarbontracker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercarbontracker',
            name='clothes_spend',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='electronics_spend',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='flights_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='protein_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='protein_type',
            field=models.CharField(default='beef', max_length=20),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='transport_type',
            field=models.CharField(default='petrol_car', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='carbon_result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='electricity_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='transport_km',
            field=models.FloatField(default=0.0),
        ),
    ]
