# Generated by Django 6.0.3 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_usercarbontracker_clothes_spend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercarbontracker',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
