# Generated by Django 6.0.3 on 2026-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_usercarbontracker_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercarbontracker',
            name='flights_hours',
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='building_type',
            field=models.CharField(choices=[('apartment_small', 'شقة صغيرة (< 80 م²)'), ('apartment_medium', 'شقة متوسطة (80–150 م²)'), ('apartment_large', 'شقة كبيرة (> 150 م²)'), ('house_small', 'بيت مستقل صغير'), ('house_large', 'بيت مستقل كبير / فيلا')], default='apartment_medium', max_length=30),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='buys_secondhand_pct',
            field=models.FloatField(default=0.0, help_text='نسبة المشتريات المستعملة %'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='carbon_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='carbon_flights',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='carbon_food',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='carbon_shopping',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='carbon_transport',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='carbon_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='carpool_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='cooling_months',
            field=models.PositiveIntegerField(default=3, help_text='عدد أشهر التبريد في السنة'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='cooling_type',
            field=models.CharField(choices=[('none', 'لا يوجد تبريد'), ('ac_inverter', 'مكيف إنفرتر'), ('ac_standard', 'مكيف عادي'), ('fan_only', 'مراوح فقط'), ('evaporative', 'مبرد تبخيري (كولر)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='diet_type',
            field=models.CharField(choices=[('omnivore', 'آكل كل شيء'), ('low_meat', 'قليل اللحوم'), ('pescatarian', 'نباتي مع أسماك'), ('vegetarian', 'نباتي'), ('vegan', 'نباتي صارم (Vegan)')], default='omnivore', max_length=20),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='driving_style',
            field=models.CharField(choices=[('city', 'مدينة'), ('highway', 'طريق سريع'), ('mixed', 'مختلط')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='flight_class',
            field=models.CharField(choices=[('economy', 'اقتصادي'), ('business', 'أعمال'), ('first', 'أول')], default='economy', max_length=10),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='flights_long_hours',
            field=models.FloatField(default=0.0, help_text='ساعات رحلات طويلة (>6 ساعات) سنوياً'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='flights_medium_hours',
            field=models.FloatField(default=0.0, help_text='ساعات رحلات متوسطة (3–6 ساعات) سنوياً'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='flights_short_hours',
            field=models.FloatField(default=0.0, help_text='ساعات رحلات قصيرة (<3 ساعات) سنوياً'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='food_waste_percent',
            field=models.FloatField(default=20.0, help_text='نسبة هدر الطعام %'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='furniture_spend',
            field=models.FloatField(default=0.0, help_text='دينار/شهر'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='has_solar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='heating_type',
            field=models.CharField(choices=[('none', 'لا يوجد تدفئة'), ('electric', 'تدفئة كهربائية'), ('natural_gas', 'غاز طبيعي'), ('lpg', 'غاز بوتاجاز (LPG)'), ('diesel_heater', 'مازوت / سولار'), ('wood', 'حطب'), ('district', 'تدفئة مركزية مشتركة')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='heating_usage',
            field=models.FloatField(default=0.0, help_text='كغ غاز أو لتر مازوت أو kWh/شهر'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='household_size',
            field=models.PositiveIntegerField(default=1, help_text='عدد أفراد الأسرة'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='local_food_percent',
            field=models.FloatField(default=50.0, help_text='نسبة الغذاء المحلي/الموسمي %'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='shopping_frequency',
            field=models.CharField(choices=[('rarely', 'نادراً (< مرة/شهر)'), ('monthly', 'شهرياً'), ('weekly', 'أسبوعياً'), ('daily', 'يومياً تقريباً')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='solar_coverage_pct',
            field=models.FloatField(default=0.0, help_text='نسبة تغطية الطاقة الشمسية %'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='uses_carpool',
            field=models.BooleanField(default=False, help_text='هل تشارك السيارة مع آخرين؟'),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='waste_recycling',
            field=models.CharField(choices=[('none', 'لا أفصل أو أعيد تدوير'), ('some', 'أفصل بعض المواد'), ('most', 'أفصل معظم المواد'), ('full', 'فصل كامل + كمبوست')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='water_source',
            field=models.CharField(choices=[('city_network', 'شبكة المياه البلدية'), ('well_pump', 'بئر + مضخة'), ('tanker', 'صهريج'), ('mixed', 'مختلط')], default='city_network', max_length=20),
        ),
        migrations.AddField(
            model_name='usercarbontracker',
            name='water_usage_liters',
            field=models.FloatField(default=0.0, help_text='لتر/يوم للفرد'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='carbon_result',
            field=models.FloatField(blank=True, help_text='كغم CO₂ / يوم', null=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='clothes_spend',
            field=models.FloatField(default=0.0, help_text='دينار/شهر'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='electricity_usage',
            field=models.FloatField(default=0.0, help_text='kWh/شهر'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='electronics_spend',
            field=models.FloatField(default=0.0, help_text='دينار/شهر'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='protein_grams',
            field=models.FloatField(default=0.0, help_text='غرام/يوم'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='protein_type',
            field=models.CharField(choices=[('beef', 'لحم بقر'), ('lamb', 'لحم خروف / ماعز'), ('pork', 'لحم خنزير'), ('poultry', 'دواجن (دجاج / ديك رومي)'), ('fish_farmed', 'أسماك مزروعة'), ('fish_wild', 'أسماك برية'), ('seafood', 'مأكولات بحرية أخرى'), ('eggs', 'بيض'), ('dairy', 'منتجات ألبان'), ('legumes', 'بقوليات (عدس / حمص / فول)'), ('tofu_tempeh', 'توفو / تمبيه'), ('nuts', 'مكسرات')], default='poultry', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='transport_km',
            field=models.FloatField(default=0.0, help_text='كم/يوم'),
        ),
        migrations.AlterField(
            model_name='usercarbontracker',
            name='transport_type',
            field=models.CharField(choices=[('petrol_small', 'سيارة بنزين صغيرة (≤1.4L)'), ('petrol_medium', 'سيارة بنزين متوسطة (1.5–2.0L)'), ('petrol_large', 'سيارة بنزين كبيرة (>2.0L / SUV)'), ('diesel_car', 'سيارة ديزل'), ('hybrid_car', 'سيارة هجينة (Hybrid)'), ('ev_car', 'سيارة كهربائية'), ('motorcycle', 'دراجة نارية'), ('bus_public', 'باص عام / حافلة'), ('minibus', 'سرفيس / ميني باص'), ('taxi', 'تاكسي'), ('bicycle', 'دراجة هوائية'), ('walking', 'مشي')], default='petrol_medium', max_length=25),
        ),
    ]
